In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,mean_squared_error
iris=datasets.load_iris()
X_class=iris.data
y_class=iris.target
X_train_class,X_test_class,y_train_class,y_test_class=train_test_split(X_class,y_class,test_size=0.3,random_state=42)
knn_classifier=KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train_class,y_train_class)
y_pred_class=knn_classifier.predict(X_test_class)
accuracy_class=accuracy_score(y_test_class,y_pred_class)
confusion_class=confusion_matrix(y_test_class,y_pred_class)
report_class=classification_report(y_test_class,y_pred_class)
print("KNN Classification Performance Metrics:")
print("Accuracy:",accuracy_class)
print("Confusion Matrix:\n",confusion_class)
print("Classification Report:\n",report_class)
boston=datasets.load_diabetes()
X_reg=boston.data
y_reg=boston.target
X_train_reg,X_test_reg,y_train_reg,y_test_reg=train_test_split(X_reg,y_reg,test_size=0.3,random_state=42)
knn_regressor=KNeighborsRegressor(n_neighbors=5)
knn_regressor.fit(X_train_reg,y_train_reg)
y_pred_reg=knn_regressor.predict(X_test_reg)
mse=mean_squared_error(y_test_reg,y_pred_reg)
print("KNN Regression Performance Metrics:")
print("Mean Squared Error:",mse)


KNN Classification Performance Metrics:
Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

KNN Regression Performance Metrics:
Mean Squared Error: 3222.117894736842
